create database "News" with owner=postgres encoding='UTF-8' lc_collate='en_US.utf8' lc_ctype='en_US.utf8' template template1;


CREATE TABLE IF NOT EXISTS public."ProposedNews"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    news_text text,
    images JSON,
    CONSTRAINT "ProposedNews_pkey" PRIMARY KEY (id)
);
